### ISSUE TITLE
Confirm before delete

### ISSUE THREAD

**Issue by rosano** [tadeussenf/pocket-wiki#10]
I was going to add a `confirm` before deleting but I'm not sure if this is the latest version of the code. It seems to connect the Archive button to `pocket.deleteItem` and vice versa, whereas in production these buttons seem to function as expected. https://github.com/tadeussenf/pocket-wiki/blob/22c0c1e507dfbff4af528991a9a4b041484e2fbe/client/src/app/item-list/item-list.component.html#L35-L45

**Comment by tadeussenf** [comment]
@rosano thank you for the heads up, this was definitely mixed up (also in the productive version). 

If you want to submit a pull request for your feature I will be happy to merge that.
