### ISSUE TITLE
Server error prevents fetch

### ISSUE THREAD

**Issue by rosano** [tadeussenf/pocket-wiki#13]
Seem like there have been no changes in the repo recently, this started a few days ago. I'm using Safari 12.1 on macOS.
<img width="1232" alt="Screen Shot 2021-02-27 at 17 46 08" src="https://user-images.githubusercontent.com/1680612/109399829-dd62fb80-7923-11eb-9043-8b7b7f3dee18.png">

**Comment by tadeussenf** [comment]
I noticed this too, seems to be a cloudfront error at first glance:

 ```
403 ERROR
The request could not be satisfied.
Bad request. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.

Generated by cloudfront (CloudFront)
Request ID: rWYl9_1kLG5kq8fB4p3KrE2yEtawTqveuMmLdEKXlzucp4mqNujpng==
```

**Comment by tadeussenf** [comment]
@rosano Not sure what changed at the pocket API, but this seems to fix it. Can you confirm this?

**Comment by rosano** [comment]
yay it works! thank you :)
