### ISSUE TITLE
Search errors

### ISSUE THREAD

**Issue by rosano** [tadeussenf/pocket-wiki#27]
Seems like the search button no longer triggers a search. Pressing `Enter` does trigger a search but results in an error:

```
TypeError: undefined is not an object (evaluating 'e.resolved_title.toLowerCase')
```

This has been the case for maybe a month or so but I haven't had time to make an issue. The code on GitHub might be different from production.

**Comment by tadeussenf** [comment]
This is probably due to one of the saved items in your pocket not having the propery "resolved_title".
I updated code and deployment, can you please check it?

**Comment by rosano** [comment]
No error when trying search with local build. Are you sure the deployment is the same? Maybe re-deploy?

**Comment by tadeussenf** [comment]
@rosano I deployed once more, pls check it :) If this does not help you please try to clear your browser cache.

**Comment by rosano** [comment]
Works! Thank you.
